# Generated by Django 2.2.18 on 2021-06-16 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Last update at')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={'ordering': ['datetime_updated'],},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Last update at')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'fetch_status',
                    models.CharField(
                        choices=[
                            ('Pending', 'Fetch Pending'),
                            ('Success', 'Fetch Success'),
                            ('Failed', 'Fetch Failed'),
                        ],
                        default='Pending',
                        max_length=50,
                    ),
                ),
                ('number_of_retries', models.IntegerField(default=0)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feeds.Feed')),
            ],
            options={'abstract': False,},
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Last update at')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('published_id', models.CharField(blank=True, max_length=250, unique=True)),
                ('published_time', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('author', models.CharField(blank=True, max_length=250)),
                ('url', models.URLField(blank=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feeds.Feed')),
            ],
            options={'ordering': ['datetime_updated'],},
        ),
    ]
